Traceback (most recent call last):
  File "c:\users\ximta\appdata\local\programs\python\python37\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\ximta\appdata\local\programs\python\python37\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\ximta\appdata\local\programs\python\python37\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\ximta\appdata\local\programs\python\python37\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\ximta\appdata\local\programs\python\python37\lib\asyncio\base_events.py", line 583, in run_until_complete
    return future.result()
  File "c:\users\ximta\appdata\local\programs\python\python37\lib\site-packages\nbclient\client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\ximta\appdata\local\programs\python\python37\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\ximta\appdata\local\programs\python\python37\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Load Packages
import numpy as np
import pandas as pd
from pandas_datareader import data
import matplotlib.pyplot as plt
%matplotlib inline

# Read Data
df = data.DataReader(['AAPL', 'NKE', 'GOOGL', 'AMZN'], 'yahoo', start='2015/01/01', end='2019/12/31')

# TSLA
tesla = test['TSLA'].pct_change().apply(lambda x: np.log(1+x))
var_tesla = tesla.var()
tesla_vol = np.sqrt(tesla.var() * 250)

# Log of Percentage change for Facebook
fb = test['FB'].pct_change().apply(lambda x: np.log(1+x))
var_fb = fb.var()
fb_vol = np.sqrt(var_fb * 250)

# Log Returns
logReturns = Data.pct_change().apply(lambda x: np.log(1+x))
MeanVec = logReturns.mean()
CovMat = logReturns.cov()

w = [0.2, 0.8]
(MeanVec * w).sum()

------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
[1;32m<ipython-input-1-7698b6b481b4>[0m in [0;36m<module>[1;34m[0m
[0;32m     10[0m [1;33m[0m[0m
[0;32m     11[0m [1;31m# TSLA[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 12[1;33m [0mtesla[0m [1;33m=[0m [0mtest[0m[1;33m[[0m[1;34m'TSLA'[0m[1;33m][0m[1;33m.[0m[0mpct_change[0m[1;33m([0m[1;33m)[0m[1;33m.[0m[0mapply[0m[1;33m([0m[1;32mlambda[0m [0mx[0m[1;33m:[0m [0mnp[0m[1;33m.[0m[0mlog[0m[1;33m([0m[1;36m1[0m[1;33m+[0m[0mx[0m[1;33m)[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     13[0m [0mvar_tesla[0m [1;33m=[0m [0mtesla[0m[1;33m.[0m[0mvar[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m     14[0m [0mtesla_vol[0m [1;33m=[0m [0mnp[0m[1;33m.[0m[0msqrt[0m[1;33m([0m[0mtesla[0m[1;33m.[0m[0mvar[0m[1;33m([0m[1;33m)[0m [1;33m*[0m [1;36m250[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mNameError[0m: name 'test' is not defined
NameError: name 'test' is not defined

